# Generated by Django 6.0.4 on 2026-04-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_task_completed_alter_task_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
