# Generated by Django 6.0.4 on 2026-04-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
