# Generated by Django 6.0.4 on 2026-04-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0008_task_shared_with_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='shared_with',
        ),
    ]
